In [1]:
import numpy as np

In [8]:
#X represents the size of a tumor in centimeters.
X=np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88])

In [5]:
X

array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69,
       5.88])

In [9]:
#Note: X has to be reshaped into a column from a row for the LogisticRegression() function to work.
X=np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)

In [7]:
X

array([[3.78],
       [2.44],
       [2.09],
       [0.14],
       [1.72],
       [1.65],
       [4.92],
       [4.37],
       [4.96],
       [4.52],
       [3.69],
       [5.88]])

In [11]:
#y represents whether or not the tumor is cancerous (0 for "No", 1 for "Yes").
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [12]:
from sklearn import linear_model

In [13]:
logr=linear_model.LogisticRegression()

In [14]:
logr.fit(X,y)

LogisticRegression()

In [20]:
predicted=logr.predict(np.array([3.46]).reshape(-1,1))

In [21]:
print(predicted)

[0]


In [23]:
log_odds = logr.coef_ 
odds = np.exp(log_odds)

print(odds)

[[4.03541657]]


In [24]:
# This tells us that as the size of a tumor increases by 1mm the odds of it being a tumor increases by 4x.

In [25]:
# Probability

In [26]:
def logit2pob(logr,x):
    log_odds=logr.coef_ * x + logr.intercept_
    odds=np.exp(log_odds)
    probability=odds / ( 1 + odds )
    return(probability)

In [27]:
print(logit2pob(logr,X))

[[0.60749955]
 [0.19268876]
 [0.12775886]
 [0.00955221]
 [0.08038616]
 [0.07345637]
 [0.88362743]
 [0.77901378]
 [0.88924409]
 [0.81293497]
 [0.57719129]
 [0.96664243]]
